#!/usr/bin/env python3
"""Build tests/corpus/threenil.txt: three bids, every answer from the oracle.

Rows cycle through all eight three-bid role arrays -- the lone bid in each seat,
its partner leaning 2 or 3 -- through every trick depth, and through both
tie-break directions, so the corpus covers the whole ladder rather than one
corner of it.  Four- and five-card rows are the bulk.  The six-card rows all
start two or three cards into a trick: from a clean lead the oracle can take a
minute or two over one, and the whole file regenerates in about a minute as it
is.

THE COLUMNS are the shared corpus format (src/nil/corpus.hpp), read the way a
three-bid deal pins them:

  nils_set     how many of the three bids break.  Pinned: the rank names the
               lone bid's fate and how many twins are down.
  nil_tricks   the three bidders' combined tricks.  The twins' share is their
               side's whole total, which is pinned; the lone bidder's share is
               pinned only while its bid holds (zero).  Once it breaks, its
               tricks count for its side like its partner's and the split is a
               witness -- so the column is `?` on those rows rather than a
               number some other correct search would contradict.
  side_tricks  the tricks of the side holding the FIRST bidder in N, E, S, W
               order, which is the side nil_cli and the C ABI report as
               `nil_side_tricks`.  Pinned.

Usage:
  tools/make_threenil_corpus.py --out tests/corpus/threenil.txt
"""

import argparse
import importlib.util
import pathlib
import random
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
spec = importlib.util.spec_from_file_location("nil_oracle", ROOT / "nil_oracle.py")
oracle = importlib.util.module_from_spec(spec)
sys.modules["nil_oracle"] = oracle
spec.loader.exec_module(oracle)

SEATS = "NESW"
RANKS = "23456789TJQKA"

SHAPES = []
for lone in range(4):
    for lean in (3, 2):
        roles = [0] * 4
        roles[(lone + 2) % 4] = lean
        SHAPES.append(roles)

# (cards, how many rows, the (depth, direction) cycle each role array walks).
PLAN = [
    (4, 64, [(d, sec) for d in range(4) for sec in ("max", "min")]),
    (5, 32, [(0, "max"), (1, "min"), (2, "max"), (3, "max")]),
    (6, 16, [(3, "max"), (2, "min")]),
]

HEADER = """\
# Three nils: one pair both bid (the TWINS), the other pair has one bid (the
# LONE bid) and one seat that did not bid, whose role is that side's lean.
# Generated by tools/make_threenil_corpus.py; every answer is nil_oracle.py's.
#
#   name | pbn | leader | seats | broken | trick | secondary | nils_set |
#   nil_tricks | side_tricks | pv | provenance
#
#   seats        four role digits clockwise from the seat the PBN names.  Three
#                0s and one 2 or 3; rows cycle through all eight arrangements
#   trick        cards already on the trick; rows cycle through depths 0 to 3
#   secondary    both directions: the ladder is the same and only the trick
#                term's sign moves, so each is pinned on its own rows
#   nils_set     0..3, how many bids break
#   nil_tricks   the three bidders' combined tricks, or `?` where the lone bid
#                breaks -- its own count is a witness from then on, since its
#                tricks count for its side like its partner's
#   side_tricks  the side holding the first bidder in N, E, S, W order
#   pv           the oracle's canonical line; checked under --check-pv
#
# THE OBJECTIVE is T's conversion rule as a ladder (nil_oracle.py, three_nil_rank;
# src/nil/seats.hpp).  With n = the lone bid makes and d = twin bids down:
#   lean 3, set theirs first   lone side's rank 2*d + n
#   lean 2, save ours first    lone side's rank 3*n + d
# and the twins' rank is 5 minus it.  Then each side's own tricks, wanted under
# secondary=max and shed under min.
"""


def to_pbn(hands):
    return "N:" + " ".join(
        ".".join("".join(RANKS[c.rank - 2] for c in sorted(
            (c for c in h if c.suit == s), key=lambda c: -c.rank)) for s in range(4))
        for h in hands)


def make_row(rng, cards, roles, depth, secondary, name):
    while True:
        deck = [oracle.Card(s, r) for s in range(4) for r in range(2, 15)]
        pick = rng.sample(deck, 4 * cards)
        hands = [sorted(pick[j * cards:(j + 1) * cards]) for j in range(4)]
        leader = rng.randrange(4)
        broken = rng.random() < 0.5
        trick = []
        for k in range(depth):
            seat = (leader + k) % 4
            card = rng.choice(oracle.legal_moves(tuple(hands[seat]), tuple(trick), broken))
            hands[seat].remove(card)
            broken = oracle.spades_broken_after(broken, tuple(trick), card)
            trick.append(card)
        pos = oracle.Position(hands=tuple(tuple(h) for h in hands), leader=leader,
                              spades_broken=broken, current_trick=tuple(trick))
        try:
            pos.validate()
        except ValueError:
            continue
        sol = oracle.solve_three_nils(pos, roles, use_memo=True, secondary=secondary)
        lone_down = bool(sol.nils_set_mask & (1 << sol.lone))
        bidders = sum(sol.seat_tricks[s] for s in [sol.lone] + sol.twins)
        first = next(s for s in range(4) if roles[s] == 0)
        side = sol.side_tricks[first % 2]
        pv = " ".join("%s:%s" % (SEATS[s], c) for s, c in sol.pv)
        return " | ".join([
            name, to_pbn(hands), SEATS[leader], " ".join(map(str, roles)),
            "1" if broken else "0", " ".join(str(c) for c in trick), secondary,
            str(sol.nils_set), "?" if lone_down else str(bidders), str(side), pv, "oracle",
        ])


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--out", default=str(ROOT / "tests/corpus/threenil.txt"))
    ap.add_argument("--seed", type=int, default=2026)
    args = ap.parse_args()
    rng = random.Random(args.seed)
    lines = [HEADER]
    for cards, count, cycle in PLAN:
        for i in range(count):
            roles = SHAPES[i % len(SHAPES)]
            depth, secondary = cycle[(i // len(SHAPES)) % len(cycle)]
            name = "t%d-%04d" % (cards, i)
            lines.append(make_row(rng, cards, roles, depth, secondary, name))
            print(name, file=sys.stderr, flush=True)
    pathlib.Path(args.out).write_text("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
