#!/usr/bin/env python3
"""Generate a corpus of positions with oracle-verified answers.

The corpus is the fast accuracy test: nil_bench replays it with no Python and no
oracle, so it can run on every build and in CI.  Regenerate it only when you
deliberately want new coverage -- the whole point is that the committed answers
came from nil_oracle.py at a moment when someone was paying attention.

  tools/make_corpus.py --out tests/corpus/positions.txt
  tools/make_corpus.py --out tests/corpus/positions.txt --spec 4:400,5:120,6:40
  tools/make_corpus.py --out extra.txt --spec 5:50 --seed 99 --append --start-index 120

Generating the default corpus takes a few minutes: the oracle is a deliberately
naive brute force and 6-card deals cost it several seconds each.
"""

from __future__ import annotations

import argparse
import importlib.util
import os
import random
import sys
import time
from typing import List, Optional, Sequence, Tuple

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import crosscheck  # noqa: E402  (same directory)

SEAT_CHARS = "NESW"

HEADER = """\
# Positions with answers from nil_oracle.py.  Generated by tools/make_corpus.py;
# do not edit by hand.
#
#   name | pbn | leader | seats | broken | trick | secondary | nils_set |
#   nil_tricks | side_tricks | pv
#
# `nil_tricks` is what the nil bidder takes under optimal play by both
# coalitions, so `nil_tricks > 0` means the nil can be forced to fail (unless
# that seat's role is 1, in which case the primary objective was switched off and the
# count is just what fell out of the secondary one).  `side_tricks` is the nil
# bidder plus its covering partner.  `secondary` is the tie-break direction.
# `pv` is informational: any future move ordering will legitimately change which
# of several equal-valued cards the search picks.
#
# spec: %(spec)s   seed: %(seed)d   trick-prob: %(trick_prob)s
# generated: %(when)s
"""


def parse_spec(text: str) -> List[Tuple[int, int]]:
    """'4:400,5:120,6:40' -> [(4, 400), (5, 120), (6, 40)]"""
    out = []
    for chunk in text.split(","):
        chunk = chunk.strip()
        if not chunk:
            continue
        cards, _, count = chunk.partition(":")
        out.append((int(cards), int(count)))
    return out


def main(argv: Optional[Sequence[str]] = None) -> int:
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument("--out", default=os.path.join("tests", "corpus", "positions.txt"))
    p.add_argument("--oracle", default=None, help="path to nil_oracle.py")
    p.add_argument("--spec", default="4:400,5:120,6:40",
                   help="cards:count pairs [4:400,5:120,6:40]")
    p.add_argument("--seed", type=int, default=20240101)
    p.add_argument("--trick-prob", type=float, default=0.35,
                   help="chance of resuming mid-trick [0.35]")
    p.add_argument("--append", action="store_true", help="append instead of overwriting")
    p.add_argument("--start-index", type=int, default=0,
                   help="first record number, for extending a corpus in chunks [0]")
    p.add_argument("--quiet", action="store_true")
    args = p.parse_args(argv)

    oracle, path = crosscheck.load_oracle(args.oracle)
    if oracle is None:
        print("make_corpus: nil_oracle.py not found (looked for %s)" % path, file=sys.stderr)
        print("             pass --oracle /path/to/nil_oracle.py", file=sys.stderr)
        return 2
    if not args.quiet:
        print("oracle: %s" % path)

    spec = parse_spec(args.spec)
    rng = random.Random(args.seed)

    directory = os.path.dirname(os.path.abspath(args.out))
    if directory and not os.path.isdir(directory):
        os.makedirs(directory)

    lines = []
    started = time.time()
    total = sum(count for _, count in spec)
    done = 0
    for cards, count in spec:
        for index in range(count):
            case = crosscheck.Case(oracle, rng, cards, args.trick_prob)
            nil_tricks, side_tricks, _opponents, pv = crosscheck.run_oracle(
                oracle, case, use_memo=True
            )
            lines.append(
                # Eleven columns, matching the header this file writes:
                #   name | pbn | leader | seats | broken | trick | secondary |
                #   nils_set | nil_tricks | side_tricks | pv
                #
                # `seats` runs clockwise from the seat the row's own PBN names,
                # which is what Case.roles_text() anchors it against.
                "c%d-%04d | %s | %s | %s | %d | %s | %s | %d | %d | %d | %s"
                % (
                    cards,
                    args.start_index + index,
                    case.pbn,
                    SEAT_CHARS[case.leader],
                    case.roles_text(),
                    1 if case.spades_broken else 0,
                    case.trick_text,
                    case.secondary,
                    # Pinned by the primary level; a bid the roles declare
                    # already broken counts toward it.
                    1 if (case.nil_already_set or nil_tricks > 0) else 0,
                    nil_tricks,
                    side_tricks,
                    pv,
                )
            )
            done += 1
            if not args.quiet and (done % 25 == 0 or done == total):
                elapsed = time.time() - started
                print(
                    "  %d/%d  (%.0fs elapsed, ~%.0fs left)"
                    % (done, total, elapsed, elapsed / done * (total - done))
                )

    mode = "a" if args.append else "w"
    with open(args.out, mode) as handle:
        if not args.append:
            handle.write(
                HEADER
                % {
                    "spec": args.spec,
                    "seed": args.seed,
                    "trick_prob": args.trick_prob,
                    "when": time.strftime("%Y-%m-%d"),
                }
            )
        handle.write("\n".join(lines))
        handle.write("\n")

    fails = sum(1 for line in lines if int(line.split("|")[9]) > 0)
    if not args.quiet:
        print(
            "\nwrote %d positions to %s in %.0fs (%d nil fails, %d nil makes)"
            % (len(lines), args.out, time.time() - started, fails, len(lines) - fails)
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
