#!/usr/bin/env python3
"""Build tests/corpus/opposed.txt: one bid on each side, every answer from the oracle.

WHY THIS CORPUS EXISTS.  Every other shape the solver answers has an oracle
corpus that checks the principal variation card for card -- positions.txt for a
single nil, multinil.txt for twins, threenil.txt for three bids.  One bid per
side had none: opposing_crosscheck.py compares the game VALUE (the utility pair)
and nothing in ctest checked an opposed line against nil_oracle.py, so a change
that kept every value and moved the canonical line on this shape could only be
caught by a differential against an older binary.  This is that missing corpus.

Rows cycle through all eight strictly opposed role arrays -- a bid on each side,
the partners leaning opposite ways, in every rotation -- through every trick
depth and through both tie-break directions.  Four- and five-card rows are the
bulk; the six-card rows start two or three cards into a trick so the oracle
finishes in seconds.

THE COLUMNS are the shared corpus format (src/nil/corpus.hpp), read the way a
bid-each-side deal pins them:

  nils_set     how many of the two bids break.  Pinned: the outcome rank names
               both bids' fates.
  nil_tricks   the two bidders' combined tricks.  Pinned only while both bids
               hold (zero); once a bid breaks its tricks count for its side like
               its partner's and the split is a witness, so the column is `?`.
  side_tricks  the tricks of the side holding the FIRST bidder in N, E, S, W
               order, which is the side nil_cli and the C ABI report as
               `nil_side_tricks`.  Pinned.
  pv           the oracle's canonical line; checked under --check-pv.

Usage:
  tools/make_opposed_corpus.py --out tests/corpus/opposed.txt
"""

import argparse
import importlib.util
import pathlib
import random
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
spec = importlib.util.spec_from_file_location("nil_oracle", ROOT / "nil_oracle.py")
oracle = importlib.util.module_from_spec(spec)
sys.modules["nil_oracle"] = oracle
spec.loader.exec_module(oracle)

SEATS = "NESW"
RANKS = "23456789TJQKA"

# Every strictly opposed arrangement, as tools/opposing_crosscheck.py builds it:
# a bid on each side, partners leaning opposite ways, in all four rotations.
SHAPES = []
for first in range(4):
    for a, b in ((2, 3), (3, 2)):
        roles = [0] * 4
        roles[(first + 2) % 4] = a   # partner of the first bidder
        roles[(first + 3) % 4] = b   # partner of the second
        SHAPES.append(roles)

PLAN = [
    (4, 64, [(d, sec) for d in range(4) for sec in ("max", "min")]),
    (5, 32, [(0, "max"), (1, "min"), (2, "max"), (3, "max")]),
    (6, 16, [(3, "max"), (2, "min")]),
]

HEADER = """\
# One bid on each side, the partners leaning opposite ways (SHAPE_OPPOSING_NILS).
# Generated by tools/make_opposed_corpus.py; every answer is nil_oracle.py's.
#
#   name | pbn | leader | seats | broken | trick | secondary | nils_set |
#   nil_tricks | side_tricks | pv | provenance
#
#   seats        four role digits clockwise from the seat the PBN names.  Two
#                0s on opposite sides and a 2 and a 3; rows cycle through all
#                eight arrangements
#   trick        cards already on the trick; rows cycle through depths 0 to 3
#   secondary    both directions: the outcome ladder is the same and only the
#                trick term's sign moves, so each is pinned on its own rows
#   nils_set     0..2, how many bids break
#   nil_tricks   the two bidders' combined tricks, or `?` where a bid breaks --
#                its own count is a witness from then on, since its tricks count
#                for its side like its partner's
#   side_tricks  the side holding the first bidder in N, E, S, W order
#   pv           the oracle's canonical line; checked under --check-pv
#
# THE OBJECTIVE is side_rank's ladder (nil_oracle.py; src/nil/seats.hpp): a
# side's own bid surviving while the other's breaks is its best outcome and the
# reverse its worst, with the partner's lean ordering the two in between, and
# the two sides' ranks summing to a constant.  Then each side's own tricks,
# wanted under secondary=max and shed under min."""


def to_pbn(hands):
    return "N:" + " ".join(
        ".".join("".join(RANKS[c.rank - 2] for c in sorted(
            (c for c in h if c.suit == s), key=lambda c: -c.rank)) for s in range(4))
        for h in hands)


def make_row(rng, cards, roles, depth, secondary, name):
    while True:
        deck = [oracle.Card(s, r) for s in range(4) for r in range(2, 15)]
        pick = rng.sample(deck, 4 * cards)
        hands = [sorted(pick[j * cards:(j + 1) * cards]) for j in range(4)]
        leader = rng.randrange(4)
        broken = rng.random() < 0.5
        trick = []
        for k in range(depth):
            seat = (leader + k) % 4
            card = rng.choice(oracle.legal_moves(tuple(hands[seat]), tuple(trick), broken))
            hands[seat].remove(card)
            broken = oracle.spades_broken_after(broken, tuple(trick), card)
            trick.append(card)
        pos = oracle.Position(hands=tuple(tuple(h) for h in hands), leader=leader,
                              spades_broken=broken, current_trick=tuple(trick))
        try:
            pos.validate()
        except ValueError:
            continue
        sol = oracle.solve_opposing_nils(pos, roles, use_memo=True, secondary=secondary)
        down = [not made for made in sol.nil_makes]
        first = next(s for s in range(4) if roles[s] == 0)
        side = sol.side_tricks[first % 2]
        bidders = sum(sol.seat_tricks[s] for s in sol.nil_of_side)
        pv = " ".join("%s:%s" % (SEATS[s], c) for s, c in sol.pv)
        return " | ".join([
            name, to_pbn(hands), SEATS[leader], " ".join(map(str, roles)),
            "1" if broken else "0", " ".join(str(c) for c in trick), secondary,
            str(sum(down)), "?" if any(down) else str(bidders), str(side), pv, "oracle",
        ])


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--out", default=str(ROOT / "tests/corpus/opposed.txt"))
    ap.add_argument("--seed", type=int, default=2026)
    args = ap.parse_args()
    rng = random.Random(args.seed)
    lines = [HEADER]
    for cards, count, cycle in PLAN:
        for i in range(count):
            roles = SHAPES[i % len(SHAPES)]
            depth, secondary = cycle[(i // len(SHAPES)) % len(cycle)]
            name = "o%d-%04d" % (cards, i)
            lines.append(make_row(rng, cards, roles, depth, secondary, name))
            print(name, file=sys.stderr, flush=True)
    pathlib.Path(args.out).write_text("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
