#!/usr/bin/env python3
"""Build corpus rows for hand sizes the oracle cannot reach head-on.

THE PROBLEM
-----------
Cost grows roughly twentyfold per extra card.  On one core the C++ solver takes
about half a second at 6 cards, fifteen at 7, and five minutes at 8; the oracle,
being Python with a dictionary for a transposition table, runs out of memory on
a typical 7-card deal before it runs out of patience.  Generating 7-, 8- and
9-card rows the way tools/make_corpus.py generates 4-, 5- and 6-card ones is not
going to happen.

THE WAY ROUND IT
----------------
Cost varies enormously *within* a hand size.  Among random 7-card deals this
script has seen node counts from one million to eighty; the cheap ones are the
skewed distributions, where following suit is forced most of the way down and
the tree never fans out.  Those positions are ordinary Spades endings, they are
just not average ones -- and they are the ones both implementations can still
solve.

So rows come in three grades, recorded in the `provenance` column:

  oracle      cheap enough that nil_oracle.py solved it independently.  This is
              real verification and it is what the 4-6 card corpus is made of.
  solver      too expensive for the oracle, cheap enough for the C++.  The
              answer is pinned from this solver, so it catches a future change
              that alters the result -- but if the solver is wrong today, the
              row records the wrong answer confidently.  A regression baseline,
              not a proof.
  unverified  too expensive for either.  No answer is recorded; the row exists
              to be timed, and to be worth solving once there is pruning.

Selection is by wall clock, which is not reproducible, so the measured node
count goes in the file for every row that got one: node counts are
deterministic, so they are what to compare against later.

  tools/make_large_corpus.py --cards 7 --verify 4 --out tests/corpus/large.txt
  tools/make_large_corpus.py --cards 8 --pin 3 --append --out tests/corpus/large.txt
  tools/make_large_corpus.py --cards 9 --timed 3 --append --out tests/corpus/large.txt
"""

from __future__ import annotations

import argparse
import os
import random
import subprocess
import sys
import time
from typing import Dict, List, Optional, Sequence

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import crosscheck  # noqa: E402

SEAT_CHARS = "NESW"

HEADER = """\
# Large positions, for hand sizes the oracle cannot reach head-on.
# Generated by tools/make_large_corpus.py; do not edit by hand.
#
#   name | pbn | leader | nil | broken | forced | trick | secondary | nilset |
#   nil_tricks | side_tricks | pv | provenance
#
# provenance says how much a row is worth:
#   oracle      nil_oracle.py solved it independently -- real verification
#   solver      pinned from the C++ solver -- a regression baseline, not a proof
#   unverified  no answer recorded; the row exists only to be timed
#
# These are deliberately NOT average deals for their size.  Cost varies by two
# orders of magnitude within a hand size, and the cheap positions -- skewed
# distributions where following suit is forced most of the way down -- are the
# only ones anything can still solve.  The expensive rows are here as benchmark
# fodder for the road to 13 cards.
#
# Some rows are dealt from three suits rather than four.  Longer hands mean
# rarer voids, which means following suit is forced more often and the tree fans
# out less -- at 8 and 9 cards that is the difference between a position
# anything can solve and one nothing can.  Spades are always in play.
#
# node counts measured by the C++ solver at generation time (deterministic,
# so they are the number to compare against later):
"""


def deal(rng: random.Random, oracle, cards: int, trick_prob: float,
         suits: int = 4) -> Dict[str, object]:
    # Restricting the deck to fewer suits makes hands longer and voids rarer,
    # which means following suit is forced more often and the tree fans out
    # less.  At 8 and 9 cards that is the difference between a position
    # anything can solve and one nothing can.  Spades are always included, so
    # the trump and breaking rules stay exercised.
    deck = [c for c in oracle.FULL_DECK if c.suit < suits]
    if len(deck) < 4 * cards:
        raise ValueError("%d suits cannot deal %d cards to four hands" % (suits, cards))
    dealt = rng.sample(deck, 4 * cards)
    hands = [list(sorted(dealt[i * cards : (i + 1) * cards])) for i in range(4)]

    leader = rng.randrange(4)
    nil_seat = rng.randrange(4)
    broken = bool(rng.getrandbits(1))
    forced = bool(rng.getrandbits(1))
    secondary = "min" if rng.getrandbits(1) else "max"
    nil_set = rng.random() < 0.2

    trick: List = []
    if rng.random() < trick_prob:
        for offset in range(rng.randrange(1, 4)):
            seat = (leader + offset) % 4
            legal = oracle.legal_moves(tuple(sorted(hands[seat])), tuple(trick), broken)
            card = rng.choice(legal)
            broken = oracle.spades_broken_after(broken, tuple(trick), card, forced)
            hands[seat].remove(card)
            trick.append(card)

    position = oracle.Position.build(
        hands, leader=leader, spades_broken=broken, current_trick=tuple(trick)
    )
    return {
        "position": position,
        "pbn": position.to_pbn(),
        "leader": leader,
        "nil_seat": nil_seat,
        "broken": broken,
        "forced": forced,
        "secondary": secondary,
        "nil_already_set": nil_set,
        "current_trick": tuple(trick),
        "trick_text": " ".join(str(c) for c in trick),
    }


def cli_args(exe: str, spec: Dict[str, object]) -> List[str]:
    args = [exe, "--pbn", spec["pbn"], "--leader", SEAT_CHARS[spec["leader"]],
            "--nil", SEAT_CHARS[spec["nil_seat"]], "--compact"]
    if spec["broken"]:
        args.append("--spades-broken")
    if spec["forced"]:
        args.append("--break-on-forced-lead")
    if spec["secondary"] == "min":
        args += ["--secondary", "min"]
    if spec["nil_already_set"]:
        args.append("--nil-already-set")
    if spec["trick_text"]:
        args += ["--trick", spec["trick_text"]]
    # nil_cli refuses more than 7 cards per hand unless told to insist, which is
    # exactly the situation this script exists for.
    args.append("--force")
    return args


def run_solver(exe: str, spec: Dict[str, object], timeout: float):
    try:
        proc = subprocess.run(
            cli_args(exe, spec), capture_output=True, text=True, timeout=timeout
        )
    except subprocess.TimeoutExpired:
        return None
    if proc.returncode != 0:
        return None
    fields = dict(
        line.split("=", 1) for line in proc.stdout.strip().split("\n") if "=" in line
    )
    return fields


def run_oracle(oracle, spec: Dict[str, object]):
    case = crosscheck.Case.__new__(crosscheck.Case)
    case.leader = spec["leader"]
    case.nil_seat = spec["nil_seat"]
    case.spades_broken = spec["broken"]
    case.break_forced = spec["forced"]
    case.secondary = spec["secondary"]
    case.nil_already_set = spec["nil_already_set"]
    case.current_trick = spec["current_trick"]
    case.position = spec["position"]
    case.pbn = spec["pbn"]
    case.trick_text = spec["trick_text"]
    return crosscheck.run_oracle(oracle, case, use_memo=True)


def row(name: str, spec: Dict[str, object], nil_tricks, side_tricks, pv: str,
        provenance: str) -> str:
    return "%s | %s | %s | %s | %d | %d | %s | %s | %d | %s | %s | %s | %s" % (
        name, spec["pbn"], SEAT_CHARS[spec["leader"]], SEAT_CHARS[spec["nil_seat"]],
        1 if spec["broken"] else 0, 1 if spec["forced"] else 0, spec["trick_text"],
        spec["secondary"], 1 if spec["nil_already_set"] else 0,
        nil_tricks, side_tricks, pv, provenance,
    )


def main(argv: Optional[Sequence[str]] = None) -> int:
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument("--out", default=os.path.join("tests", "corpus", "large.txt"))
    p.add_argument("--exe", default=os.path.join("build", "bin", "nil_cli"))
    p.add_argument("--oracle", default=None)
    p.add_argument("--cards", type=int, required=True)
    p.add_argument("--verify", type=int, default=0, metavar="N",
                   help="emit N rows cheap enough for the oracle to confirm")
    p.add_argument("--pin", type=int, default=0, metavar="N",
                   help="emit N rows pinned from the solver (no oracle)")
    p.add_argument("--timed", type=int, default=0, metavar="N",
                   help="emit N rows with no recorded answer, for timing only")
    p.add_argument("--solver-timeout", type=float, default=4.0,
                   help="wall-clock cap when screening for cheap positions [4]")
    p.add_argument("--oracle-node-budget", type=int, default=3000000,
                   help="skip oracle verification above this solver node count, "
                        "since its memo runs the machine out of memory [3e6]")
    p.add_argument("--suits", type=int, default=4, choices=(2, 3, 4),
                   help="deal from this many suits; fewer means longer hands, "
                        "rarer voids and a far smaller tree [4]")
    p.add_argument("--trick-prob", type=float, default=0.3)
    p.add_argument("--seed", type=int, default=1)
    p.add_argument("--start-index", type=int, default=0)
    p.add_argument("--tries", type=int, default=400,
                   help="give up after this many candidate deals [400]")
    p.add_argument("--append", action="store_true")
    p.add_argument("--quiet", action="store_true")
    args = p.parse_args(argv)

    oracle, path = crosscheck.load_oracle(args.oracle)
    if oracle is None and args.verify:
        print("make_large_corpus: nil_oracle.py not found (%s)" % path, file=sys.stderr)
        return 2
    if not os.path.exists(args.exe):
        print("make_large_corpus: %s not found; build first" % args.exe, file=sys.stderr)
        return 2

    rng = random.Random(args.seed)
    want_verify, want_pin, want_timed = args.verify, args.pin, args.timed
    lines: List[str] = []
    notes: List[str] = []
    index = args.start_index
    started = time.time()

    for attempt in range(args.tries):
        if not (want_verify or want_pin or want_timed):
            break
        spec = deal(rng, oracle, args.cards, args.trick_prob, args.suits)
        fields = run_solver(args.exe, spec, args.solver_timeout)

        if fields is None:
            # The solver could not finish inside the screening window.  That is
            # exactly what a timed-only row is for.
            if want_timed:
                name = "c%d-%04d" % (args.cards, index)
                lines.append(row(name, spec, "?", "?", "", "unverified"))
                notes.append("#   %s  solver did not finish within %.0fs"
                             % (name, args.solver_timeout))
                index += 1
                want_timed -= 1
                if not args.quiet:
                    print("  %s  timed only" % name)
            continue

        nodes = int(fields["nodes"])
        name = "c%d-%04d" % (args.cards, index)

        if want_verify and nodes <= args.oracle_node_budget and oracle is not None:
            t0 = time.time()
            nil_tricks, side_tricks, _opp, pv = run_oracle(oracle, spec)
            elapsed = time.time() - t0
            if str(nil_tricks) != fields["tricks"] or str(side_tricks) != fields["side_tricks"]:
                print("DISAGREEMENT on %s\n  %s" % (name, " ".join(cli_args(args.exe, spec))),
                      file=sys.stderr)
                print("  solver nil=%s side=%s, oracle nil=%d side=%d"
                      % (fields["tricks"], fields["side_tricks"], nil_tricks, side_tricks),
                      file=sys.stderr)
                return 1
            if pv != fields["pv"]:
                print("PV DISAGREEMENT on %s\n  %s" % (name, " ".join(cli_args(args.exe, spec))),
                      file=sys.stderr)
                return 1
            lines.append(row(name, spec, nil_tricks, side_tricks, pv, "oracle"))
            notes.append("#   %s  %d nodes, oracle took %.0fs" % (name, nodes, elapsed))
            index += 1
            want_verify -= 1
            if not args.quiet:
                print("  %s  oracle verified (%d nodes, %.0fs)" % (name, nodes, elapsed))
            continue

        if want_pin:
            lines.append(row(name, spec, fields["tricks"], fields["side_tricks"],
                             fields["pv"], "solver"))
            notes.append("#   %s  %d nodes" % (name, nodes))
            index += 1
            want_pin -= 1
            if not args.quiet:
                print("  %s  pinned from the solver (%d nodes)" % (name, nodes))

    if not lines:
        print("no rows produced in %d tries" % args.tries, file=sys.stderr)
        return 1

    directory = os.path.dirname(os.path.abspath(args.out))
    if directory and not os.path.isdir(directory):
        os.makedirs(directory)
    with open(args.out, "a" if args.append else "w") as handle:
        if not args.append:
            handle.write(HEADER)
        handle.write("\n".join(notes) + "\n")
        handle.write("\n".join(lines) + "\n")

    if not args.quiet:
        print("\nwrote %d rows to %s in %.0fs" % (len(lines), args.out, time.time() - started))
        if want_verify or want_pin or want_timed:
            print("still wanted: %d verified, %d pinned, %d timed -- raise --tries"
                  % (want_verify, want_pin, want_timed))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
